### ISSUE TITLE
Image file path syntax results in no images displayed in GUI

### ISSUE THREAD

**Issue by K4KDR** [jmason86/MinXSS_Beacon_Decoder#16] opened 2017-04-26 03:08 UTC
This has been an issue since day-1 for me but I had been manually editing ui_mainWindow.py as a work-around.

In ui_mainWindow.py, image file paths show with ":/".

Only by changing these paths to start with "./" do I see images in the GUI.  Obviously this is a work-around on my part; if there is a more proper fix, information on how to configure my system to not require this manual editing would be appreciated.  I am not aware if this issue is specific to my system only, or common for everyone.

Thank you!

GUI with code as delivered:

![screenshot from 2017-04-25 22-56-23](https://cloud.githubusercontent.com/assets/19886368/25416410/b491ab72-2a0b-11e7-9ce4-f18157d655b2.png)

GUI with image file paths modified:

![screenshot from 2017-04-25 22-59-32](https://cloud.githubusercontent.com/assets/19886368/25416434/d5cd3a36-2a0b-11e7-9b94-9a9e6b8b8173.png)

**Comment by jmason86** [comment] 2017-04-26 16:08
Others have the same issue. If you look at the screenshots on twitter, most don't have the icons and images unless they've done the same as you. It even happens to me until I tried your patch. I know what the issue is: need to do pyside-rcc in addition to the pyside-uic that generates the code. I've had this as a task to work out also since day 1. I spent some time on it initially but it didn't work so I've gotta figure out the idiosyncrasies. 

I have no idea why pyside-uic generates :/ instead of ./. Seems like a wacky default. 

Note to self: at worst I can have another make.sh style file that calls pyside-uic, removes the _rc line of code in the .py, and replaces the :/ with ./ in the .py.

**Comment by jmason86** [comment] 2017-04-26 17:02
Alright.. should be fixed! ce1c731. 
For the record, this was the problem and solution: http://stackoverflow.com/questions/28480902/pyside-rcc-dyld-library-not-loaded/28502438

**Comment by K4KDR** [comment] 2017-04-26 17:09
Confirmed good w/ Ubuntu 16.04 - great work!  With no file modifications, images appear on Connect Bar and other tabs.

![screenshot from 2017-04-26 13-07-45](https://cloud.githubusercontent.com/assets/19886368/25447024/81f08ce4-2a81-11e7-96db-f1c0601537f3.png)

**Comment by jmason86** [comment] 2017-04-26 17:19
Sweet!! That one was a long time coming. Closing the issue.

**Closed by jmason86** 2017-04-26 17:19 UTC

**Comment by jmason86** [comment] 2017-04-27 02:11
Did we already send you a MinXSS polo shirt?

**Comment by K4KDR** [comment] 2017-04-27 02:31
No, wasn't aware there was any such thing.  Very kind of you to ask.

I'm sure that any number of amateurs are anxious to help; of course I'm
very happy to have been setup to give you some feedback and am anxious to
do anything that I can as the project continues.  All these years in I.T.
should be good for something!

If I can be so bold as to take your question as an offer, I would be an
"XL". :) , and thank you.

======================

**Comment by jmason86** [comment] 2017-04-27 02:56
For sure. If you email me (james.mason@lasp.colorado.edu) an address, you'll have a shirt arrive in a week or two!
