### ISSUE TITLE
"Complete Pass" button Terminal Message

### ISSUE THREAD

**Issue by K4KDR** [jmason86/MinXSS_Beacon_Decoder#12] opened 2017-04-21 21:37 UTC
Using commit 585833f, replayed recorded audio from MinXSS-1 pass 21-Apr-2017 @ 1949 UTC. 84 packets decoded using alternative Windows software.
When clicking "Complete Pass" button, the following appears in the terminal window:

```
/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py:141: FutureWarning: CTR mode needs counter parameter, not IV
  self._cipher = factory.new(key, *args, **kwargs)
```

**Comment by jmason86** [comment] 2017-04-24 17:20
Hm... that seems to be a warning not an error. Annoying but not an issue. I did actually receive your data! Since it did work as intended, I'm going to close the issue. Hopefully it doesn't come back to haunt me.

**Closed by jmason86** 2017-04-24 17:20 UTC
